include:
  - infra.yaml

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DATABASE_URL: postgresql://scale:scale@db/scale_av_cutter
    depends_on:
      db:
        condition: service_healthy
