"""added thumbnail column to talk table

Revision ID: 1aca5a6606ff
Revises: f4be1f4db0e4
Create Date: 2024-01-14 11:08:03.994851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aca5a6606ff'
down_revision = 'f4be1f4db0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talk', schema=None) as batch_op:
        batch_op.drop_index('ix_talk_path')

    op.drop_table('talk')
    with op.batch_alter_table('room_day', schema=None) as batch_op:
        batch_op.drop_index('room_day_index')

    op.drop_table('room_day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_day',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('room', sa.TEXT(), nullable=False),
    sa.Column('day', sa.TEXT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('vid', sa.TEXT(), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=False),
    sa.Column('checked_out_by', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_day', schema=None) as batch_op:
        batch_op.create_index('room_day_index', ['room', 'day'], unique=False)

    op.create_table('talk',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('room_day_id', sa.INTEGER(), nullable=True),
    sa.Column('path', sa.TEXT(), nullable=False),
    sa.Column('speakers', sa.TEXT(), nullable=False),
    sa.Column('sched_start', sa.TEXT(), nullable=False),
    sa.Column('sched_end', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=False),
    sa.Column('start', sa.INTEGER(), nullable=False),
    sa.Column('end', sa.INTEGER(), nullable=False),
    sa.Column('review_status', sa.VARCHAR(), nullable=False),
    sa.Column('edit_status', sa.VARCHAR(), nullable=False),
    sa.Column('last_edited_by', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['room_day_id'], ['room_day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('talk', schema=None) as batch_op:
        batch_op.create_index('ix_talk_path', ['path'], unique=False)

    # ### end Alembic commands ###
